import { FrameTemplate } from './types';

export const STATIC_FRAMES: FrameTemplate[] = [
  {
    id: 'frame-karta-81-kemerdekaan',
    name: 'Karang Taruna HUT RI 81 (Twin Strip 3-Pose)',
    overlayUrl: '/frames/karta-81-kemerdekaan.svg',
    badgeText: 'KARANG TARUNA EDITION',
    borderColor: '#0052FF',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-2',
    name: 'Classic Vintage (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-2.svg',
    borderColor: '#FF3366',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-3',
    name: 'Retro Aesthetic (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-3.svg',
    borderColor: '#FFE600',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-4',
    name: 'Minimalist Black (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-4.svg',
    borderColor: '#00C853',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-5',
    name: 'Fun & Playful (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-5.svg',
    borderColor: '#9C27B0',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-6',
    name: 'Modern Bold (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-6.svg',
    borderColor: '#FF9800',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-7',
    name: 'Elegant Pastel (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-7.svg',
    borderColor: '#00BCD4',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-8',
    name: 'Cyberpunk Vibe (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-8.svg',
    borderColor: '#E91E63',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-9',
    name: 'Summer Party (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-9.svg',
    borderColor: '#3F51B5',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-10',
    name: 'Neon Glow (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-10.svg',
    borderColor: '#8BC34A',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-11',
    name: 'Y2K Pop (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-11.svg',
    borderColor: '#FF5722',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-12',
    name: 'Film Roll (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-12.svg',
    borderColor: '#673AB7',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-13',
    name: 'Cute Doodle (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-13.svg',
    borderColor: '#009688',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-14',
    name: 'Monochrome Chic (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-14.svg',
    borderColor: '#CDDC39',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-15',
    name: 'Golden Celebration (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-15.svg',
    borderColor: '#EA4C89',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-16',
    name: 'Kawaii Pink (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-16.svg',
    borderColor: '#2196F3',
    aspectRatio: '2:3',
    isActive: true,
  },
  {
    id: 'frame-17',
    name: 'Urban Streetwear (Twin Strip 3-Pose)',
    overlayUrl: '/frames/frame-17.svg',
    borderColor: '#4CAF50',
    aspectRatio: '2:3',
    isActive: true,
  },
];

